/*PERFORMANCE PROBLEMS*/

/*1- DEALING WITH SUPER JSONS
Loaded Jsons have very bad performance (0.1 sec access), but if I create a similar object in SC, it has the normal very good performance!!!!
 Is there anything wrong with the load of JSON?

*/





/*2- DEALINNG WITH BIG DATASET COLLECTION
Seems unreasonable to load everything into RAM:

* Use VDiskin, (we can select start in cueSoundFile), maybe glitch?
* Dynamically allocate and free Buffers

*/